[window]
dimensions = { columns = 128, lines = 32 }
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.98
blur = false

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }

